services:
  fastleads:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: https://xgvqukojnhmobhcvhjsy.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: sb_publishable_U2hJ-NxfkFIHYGPrulJfCA_u6VADmSf
    container_name: fastleads-app
    restart: always
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-fastleads}.rule=Host(`${COMPOSE_PROJECT_NAME:-fastleads}.${TRAEFIK_HOST:-srv1656135.hstgr.cloud}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-fastleads}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-fastleads}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:-fastleads}.loadbalancer.server.port=3000"
    env_file:
      - .env.production
